config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/auth'

  root to: 'home#index'

  devise_for :users, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/edit-profile" => "devise/registrations#edit"
  end

  resources :comments
  
  resources :notes

  resources :tags

  resources :responsibilities

  resources :projects do
    get :all_tasks, on: :collection
    get :on_hold, on: :collection
    get :complete, on: :collection
    resources :tasks do 
      get :complete, on: :collection
    end
  end

  namespace :admin do 
    resources :dashboard, only: [:index]
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments
  has_many :task_tags
  has_many :tags, through: :task_tags

  enum status: [:active, :on_hold, :complete]
  enum priority: [:low, :medium, :high, :urgent]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  #custom writer and readers for Task for creating nested attributes

  def tag_names=(tags)
    tag_array = tags.split(",").map{|tag| tag.strip}
    tag_array.each do |tag|
      new_tag = Tag.find_or_create_by(name: tag)
      self.tags << new_tag
    end
  end

  def tag_names
    tags = self.tags.collect {|tag| tag.name}
    tags.join(", ")
  end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user, except: [:destroy]
  before_action :set_task, except: [:index, :new, :create]
  before_action :set_project

  def index

    @tasks = @user.tasks
    @task = Task.new
  end

  def new
    redirect_to project_tasks_path
  end

  def create
    @task = Task.create(task_params)
    redirect_to project_tasks_path
  end

  def show
    @comment = Comment.new
  end

  def edit
    redirect_to project_task_path(@project, @task)
  end

  def update
    binding.pry
    @task.tags.clear
    @task.update(task_params)
    redirect_to project_tasks_path
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path
  end

  def complete
    @complete = Task.complete
  end

  private
  def set_user
    @user = current_user
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :project_id, :user_id, :due_date, :status, :priority, :tag_names)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [project, task] do |f| %>
  <%= f.label :name %>
    <%= f.text_field :name %>
  <%= f.label :description %>
    <%= f.text_field :description %>
  <%= f.label :due_date %>
    <%= f.date_select(:due_date, :order => [:month, :day, :year]) %>
  <%= f.label :status %>
    <% Task.statuses.each do |s,index| %>
      <%= s.capitalize %>
      <%= f.radio_button :status, s %>
    <% end %>
  <%= f.label :priority %>
    <% Task.priorities.each do |p,index| %>
      <%= p.capitalize %>
      <%= f.radio_button :priority, p %>
    <% end %>
  <%= f.label :tag_names, "Tags (Comma seperated)" %>
    <%= f.text_field :tag_names %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :project_id, value: @project.id %>
  <%= f.submit %>
<% end %>

app/views/tasks/complete.html.erb
<h1> Completed Tasks </h1>

<% @complete.each do |task| %>
  <%= task.name %>
  <% end %>

app/views/tasks/index.html.erb
<h1>Project Tasks#Index</h1>

<%= render partial: "form", locals: {project: @project, task: @task} %>


<h3> <%= @project.name %> </h3>
<% @project.tasks.each do |task| %>
  <h4><%= task.name %></h4>
  <p><%= task.description %></p>
  <p>Due: <%= task.due_date %></p>
  <p>Status: <%= task.status %></p>
  <p>Priority: <%= task.priority%></p>
  <p>Tags: <% task.tags.each do |tag| %>
    <%= tag.name %>, 
    <% end %></p>
  <p><%= link_to "Edit Task", project_task_path(@project, task)%></p>
  <p><%= link_to "Delete Task", project_task_path(@project, task), method: :delete%></p>
<% end %>

app/views/tasks/show.html.erb
<h1>Edit Task</h1>
<%= render partial: "form", locals: {project: @project, task: @task} %>


<h2>Comments</h2>
<% @task.comments.reverse.each do |comment| %>
  <p> <%= comment.description %> by <%= comment.user.email %> 
  <%= link_to "Edit Comment", edit_comment_path(comment) %> 
  <%= link_to "Delete", comment_path(comment), method: :delete %></p>
<% end %>

<h2>New Comment</h2>
<%= render partial: "comments/form", locals: {comment: @comment} %>