config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/auth'

  root to: 'home#index'

  devise_for :users, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/edit-profile" => "devise/registrations#edit"
  end

  resources :comments
  
  resources :notes

  resources :tags

  resources :responsibilities

  resources :projects do
    get :all_tasks, on: :collection
    get :on_hold, on: :collection
    get :complete, on: :collection
    resources :tasks do 
      get :complete, on: :collection
    end
  end

  namespace :admin do 
    resources :dashboard, only: [:index]
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :tags, through: :tasks
  has_many :comments, through: :tasks
  enum status: [:active, :on_hold, :complete]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  validates :name, :description, :due_date, :status, presence: true
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :tags

  enum status: [:active, :complete]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :task_tags
  has_many :tasks, through: :task_tags
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments
  has_many :task_tags
  has_many :tags, through: :task_tags

  enum status: [:active, :on_hold, :complete]
  enum priority: [:low, :medium, :high, :urgent]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  #custom writer and readers for Task for creating nested attributes

  def tag_names=(tags)
    tag_array = tags.split(",").map{|tag| tag.strip}
    tag_array.each do |tag|
      new_tag = Tag.find_or_create_by(name: tag)
      self.tags << new_tag
    end
  end

  def tag_names
    tags = self.tags.collect {|tag| tag.name}
    tags.join(", ")
  end



end

app/models/task_tag.rb
class TaskTag < ActiveRecord::Base
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :projects
  has_many :responsibilities
  has_many :comments
  has_many :tasks
  has_many :notes  

  enum role: [:user, :admin]

  def tags
    tags = self.tasks.collect do |task|
      task.tags.collect {|tag| tag}
    end.flatten
  end

  def active_projects
    self.projects.active 
  end

  def complete_projects
    self.projects.active 
  end

  def on_hold_projects
    self.projects.on_hold
  end

  # Tasks are nested under projects, so we need a custom method to find all of a user's tasks
  def all_user_tasks
    self.projects.map do |project|
      project.tasks
    end.flatten
  end

  def all_tasks_query
    Task.where(project_id: self.project_ids).where("user_id = ?", self.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
  end
  def create
    @comment = Comment.create(comment_params)
    redirect_to project_task_path(find_project, find_task)
  end

  def edit
    @task = @comment.task
  end

  def update
    @comment.update(comment_params)
    redirect_to project_task_path(find_project, find_task)
  end

  def destroy
    @comment.destroy
    redirect_to project_task_path(find_project, find_task)
  end


  private
  def set_user
    @user = current_user
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def find_task
    Task.find_by(id: @comment.task_id)
  end

  def find_project
    Project.find_by(id: find_task.project_id)
  end

  def comment_params
    params.require(:comment).permit(:description, :task_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_user, except: [:destroy]
  before_action :set_note, except: [:index, :new, :create]

  def index
    @notes = @user.notes
    @note = Note.new
  end

  def new

  end

  def create
    @note = Note.create(note_params)
    redirect_to notes_path
  end

  def show
  end

  def edit 
    redirect_to note_path(@note)
  end

  def update
    @note.update(note_params)
    redirect_to notes_path
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def set_user
    @user = current_user
  end

  def set_note
    @note = Note.find_by(id: params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :description, :user_id, :status)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_user
  before_action :set_tag, only: [:update, :destroy]

  def index
    @tags = @user.tags
  end

  def update
    @tag.update(name: params[:tag][:name])
    redirect_to tags_path
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end

  private
  def set_user
    @user = current_user
  end

  def set_tag
    @tag = Tag.find_by(id: params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user, except: [:destroy]
  before_action :set_task, except: [:index, :new, :create]
  before_action :set_project

  def index

    @tasks = @user.tasks
    @task = Task.new
  end

  def new
    redirect_to project_tasks_path
  end

  def create
    @task = Task.create(task_params)
    redirect_to project_tasks_path
  end

  def show
    @comment = Comment.new
  end

  def edit
    redirect_to project_task_path(@project, @task)
  end

  def update
    binding.pry
    @task.tags.clear
    @task.update(task_params)
    redirect_to project_tasks_path
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path
  end

  def complete
    @complete = Task.complete
  end

  private
  def set_user
    @user = current_user
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :project_id, :user_id, :due_date, :status, :priority, :tag_names)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_logged_in.html.erb
<h1>Your Stats</h1>

<h3> <%= link_to "#{@user.projects.count} projects", projects_path %></h3>
  <h5> <%= @user.projects.active.count %> active</h5>
  <h5> <%= @user.projects.complete.count %> complete</h5>
  <h5> <%= @user.projects.on_hold.count %> on hold</h5>

<h3> <%= link_to "#{@user.all_user_tasks.count} tasks", all_tasks_projects_path %></h3>
  <h5> <%= @user.tasks.active.count %> active</h5>
  <h5> <%= @user.tasks.complete.count %> complete</h5>
  <h5> <%= @user.tasks.on_hold.count %> on hold</h5>

<h3> <%= link_to "#{@user.notes.count} notes", notes_path %></h3>

<h3> <%= link_to "#{@user.comments.count} comments", comments_path %></h3>

<h3> <%= link_to "#{@user.tags.count} tags", tags_path %></h3>

app/views/home/_logged_out.html.erb
<h1>Are you ready to start using the world's favorite personal project management app?</h1>


<h3>The Best Features</h3>

<p>And you know, I'm tired ... I'm so tired of pretending like my life
isn't perfect and bitchin' and just winning every second .... And I'm not
perfect and bitchin', and just delivering the goods at every frickin' turn.
.... And then, I just got to add this: There was a whole firestorm
yesterday about Brooke being, you know, a part of our crew. And let me just
say this ... this is all I'm gonna say about it: Where there were four ...
there are now three. Goodbye, Brooke, and good luck in your travels ...
you're gonna need it ... badly... So .... THE BIBLE GRIPPERS! You know?
Dealing with soft targets, and it's just strafing runs in my underwear
before my first cup of coffee because I don't have time for these clowns. I
don't have time for their judgment and their stupidity and .... (sighs) 
Yeah. I did. Because he's nothing shy of that. And it is his job to go out
there and embarrass people. Embarrass them. Not just beat them, but
embarrass them in the process.  </p>




<h3>Free for life</h3>

<p>I'm gonna hang out with these two smokin' hotties and fly privately
around the world. You know, it might be lonely up here, but I sure like the
view, Alex.  So if you think about it, dude, it's like I'm 0-for-3 with
marriage, with ne'er an excuse. And I'm like ... guys, it's right there in
the thing. Duh! We work for the Pope. We murder people. We're Vatican
assassins. And they're gonna fuel the battle-cry of my deadly and dangerous
secret and silent soldiers. 'Cause they're all around you .... Anyway.
Thought you were just messing with one dude. Sorry! WINNING! And Alex, try
to get your mind around this, as a fellow warrior, deep in the trenches:
Their entire manifesto is built upon complete and total surrender ... or
the concept of complete and total surrender. They have zero. They have that
night, and I wil Boom. Print that, people. See where that goes. </p>

app/views/home/index.html.erb
<% if current_user && user_signed_in? %>
  <%= render "logged_in" %>
<% else %>
  <%= render "logged_out" %>
<% end %>