config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/auth'

  root to: 'home#index'

  devise_for :users, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/edit-profile" => "devise/registrations#edit"
  end

  resources :comments
  
  resources :notes

  resources :tags

  resources :responsibilities

  resources :projects do
    get :all_tasks, on: :collection
    get :on_hold, on: :collection
    get :complete, on: :collection
    resources :tasks do 
      get :complete, on: :collection
    end
  end

  namespace :admin do 
    resources :dashboard, only: [:index]
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :tags, through: :tasks
  has_many :comments, through: :tasks
  enum status: [:active, :on_hold, :complete]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  validates :name, :description, :due_date, :status, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user, except: [:destroy]
  before_action :set_project, except: [:index, :new, :create]
  layout "projects_layout", except: [:all_tasks]

  def index
    @projects = @user.active_projects
    @project = Project.new
  end

  def new

  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      @projects = @user.projects
      @project
      render :index
    end
  end

  def show
  end

  def edit 
    redirect_to project_path(@project)
  end

  def update
    if (@project.status == "complete" && project_params[:status] == "active")
      @project.update(project_params)
      redirect_to project_path(@project)
    elsif @project.status == "complete"
      render :show
    else
      @project.update(project_params)
      redirect_to project_path(@project)
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def complete
    @projects = @user.complete_projects
  end

  def all_tasks
    @tasks = @user.all_user_tasks
  end

  private
  def set_user
    @user = current_user
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :user_id, :due_date, :status)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% if project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(project.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(project, class: "form-inline") do |f| %>
  <div class="form-group">
  <%= f.label :name, class: "control-label"%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :description, class: "control-label"%>
    <%= f.text_field :description,  class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :due_date, class: "control-label"%>
    <%= f.date_select :due_date, :order => [:month, :day, :year], class: "form-control"%>
  </div>
  <div class="form-group">
  <%= f.label :status, class: "control-label"%>
    <% Project.statuses.each do |s,index| %>
      <%= s.capitalize %>
      <%= f.radio_button :status, s %>
    <% end %>
  <div class="form-group">
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.submit class: "btn btn-default"%>
<% end %>

app/views/projects/_subnav.html.erb
<nav>
  <ul>
    <li><%= link_to "Active", root_path %></li>
    <li><%= link_to "Complete", complete_projects_path %></li>
  <ul>
</nav>

app/views/projects/all_tasks.html.erb
<% @tasks.each do|task| %>
  <h3> <%= link_to task.name, project_path(task.project) %> </h3>
  <p> <%= task.description %> </p>
  <p> <%= task.due_date %> </p>
<% end %>

app/views/projects/complete.html.erb
<h2>Complete Projects</h2>

<% @projects.each do|project| %>
  <h3> <%= link_to project.name, project_path(project) %> </h3>
  <p> <%= project.description %> </p>
  <p> <%= project.due_date %> </p>
  <p> <%= project.status %> </p>
  <p> <%= link_to "Project Tasks", project_tasks_path(project)%> </p>
<% end %>

app/views/projects/edit.html.erb
<%= render partial: "form", locals: {project: @project} %>

app/views/projects/index.html.erb
<h1>Projects#Index</h1>

<%= render partial: "form", locals: {project: @project} %>

<% @projects.each do|project| %>
  <h3> <%= link_to project.name, project_path(project) %> </h3>
  <p> <%= project.description %> </p>
  <p> <%= project.due_date %> </p>
  <p> <%= project.status %> </p>
  <p> <%= link_to "Project Tasks", project_tasks_path(project)%> </p>

<% end %>

app/views/projects/show.html.erb
<h3> <%= @project.name %> </h3>
<p> <%= @project.description %> </p>
<p> <%= @project.due_date %> </p>
<p> <%= @project.status %> </p>

<%= render partial: "form", locals: {project: @project} %>

<p> <%= button_to "Delete Project", project_path(@project), method: :delete, class: "btn btn-default"%> </p>