config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/auth'

  root to: 'home#index'

  devise_for :users, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    get "/edit-profile" => "devise/registrations#edit"
  end

  resources :comments
  
  resources :notes

  resources :tags

  resources :responsibilities

  resources :projects do
    get :all_tasks, on: :collection
    get :on_hold, on: :collection
    get :complete, on: :collection
    resources :tasks do 
      get :complete, on: :collection
    end
  end

  namespace :admin do 
    resources :dashboard, only: [:index]
  end

  get '/auth/facebook/callback' => 'sessions#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :tags, through: :tasks
  has_many :comments, through: :tasks
  enum status: [:active, :on_hold, :complete]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  validates :name, :description, :due_date, :status, presence: true
end

app/models/responsibility.rb
class Responsibility < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :tags

  enum status: [:active, :complete]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :task_tags
  has_many :tasks, through: :task_tags
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments
  has_many :task_tags
  has_many :tags, through: :task_tags

  enum status: [:active, :on_hold, :complete]
  enum priority: [:low, :medium, :high, :urgent]

  scope :complete, -> { where(status: 2) }
  scope :on_hold, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}

  #custom writer and readers for Task for creating nested attributes

  def tag_names=(tags)
    tag_array = tags.split(",").map{|tag| tag.strip}
    tag_array.each do |tag|
      new_tag = Tag.find_or_create_by(name: tag)
      self.tags << new_tag
    end
  end

  def tag_names
    tags = self.tags.collect {|tag| tag.name}
    tags.join(", ")
  end



end

app/models/task_tag.rb
class TaskTag < ActiveRecord::Base
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :projects
  has_many :responsibilities
  has_many :comments
  has_many :tasks
  has_many :notes  

  enum role: [:user, :admin]

  def tags
    tags = self.tasks.collect do |task|
      task.tags.collect {|tag| tag}
    end.flatten
  end

  def active_projects
    self.projects.active 
  end

  def complete_projects
    self.projects.active 
  end

  def on_hold_projects
    self.projects.on_hold
  end

  # Tasks are nested under projects, so we need a custom method to find all of a user's tasks
  def all_user_tasks
    self.projects.map do |project|
      project.tasks
    end.flatten
  end

  def all_tasks_query
    Task.where(project_id: self.project_ids).where("user_id = ?", self.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_user, except: [:destroy]
  before_action :set_note, except: [:index, :new, :create]

  def index
    @notes = @user.notes
    @note = Note.new
  end

  def new

  end

  def create
    @note = Note.create(note_params)
    redirect_to notes_path
  end

  def show
  end

  def edit 
    redirect_to note_path(@note)
  end

  def update
    @note.update(note_params)
    redirect_to notes_path
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def set_user
    @user = current_user
  end

  def set_note
    @note = Note.find_by(id: params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :description, :user_id, :status)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_user
  before_action :set_tag, only: [:update, :destroy]

  def index
    @tags = @user.tags
  end

  def update
    @tag.update(name: params[:tag][:name])
    redirect_to tags_path
  end

  def destroy
    @tag.destroy
    redirect_to tags_path
  end

  private
  def set_user
    @user = current_user
  end

  def set_tag
    @tag = Tag.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_base.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails PM", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><%= link_to "Home", root_path %></li>
        <% if current_user && user_signed_in? %>
          <% if current_user.admin? %>
            <%= render "/admin/dashboard/nav" %>
          <% end %>
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Comments", comments_path %></li>
          <li><%= link_to "Tags", tags_path %></li>
          <li><%= link_to "Responsibilities", responsibilities_path %></li>
          <li><%= link_to "Notes", notes_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      <ul>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/base"%>
    <%= yield %>

  </body>
</html>

app/views/layouts/projects_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/base" %>
    <h1>Projects</h1>
    <nav class="navbar navbar-default">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sort By <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Active", projects_path %></li>
          <li><%= link_to "Complete", complete_projects_path %></li>
            </ul>
          </li>
        <ul>
    </div>
    </nav>
    <%= yield %>

  </body>
</html>